---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: goof
spec:
  replicas: 1
  strategy: {}
  selector:
    matchLabels:
      app: goof
  template:
    metadata:
      labels:
        app: goof
    spec:
      containers:
      - image: <<DOCKERID>>/goof:dev #Edit with your Docker Hub ID
        name: goof
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        resources: {}
        env: 
          - name: "DOCKER"
            value: "1"
      restartPolicy: Always
    
---
apiVersion: v1
kind: Service
metadata:
  name: goof
spec:
  ports:
  - name: "30000"
    port: 30000
    targetPort: 3000
  selector:
    app: goof
  type: LoadBalancer
