apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-data
  labels:
    name: mongo-data
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 4Gi
  storageClassName: standard
  hostPath:
    path: /data/mongo